config/routes.rb
Blog::Application.routes.draw do

  resources :sites do
    resources :posts, only: [:show] do
      resources :comments, only: [:create, :edit, :update, :destroy]
    end
    resource :admin, only: [:show] do
      resources :posts, except: [:show, :index], controller: 'admin/posts'
    end
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users

  root 'sites#index'

end

app/views/admins/_sidenavi.html.erb
<div class="span3 bs-docs-sidebar">
  <ul class="nav nav-list bs-docs-sidenav affix">
    <li><a href="<%= site_admin_path (current_user.site) %>"><i class="icon-chevron-right"></i> 投稿した記事</a></li>
    <li><a href="<%= new_site_admin_post_path (current_user.site) %>"><i class="icon-chevron-right"></i> 新規投稿</a></li>
    <li><a href="<%= edit_site_path (current_user.site) %>"><i class="icon-chevron-right"></i> ブログ設定</a></li>
    <li><a href="<%= edit_user_path (current_user) %>"><i class="icon-chevron-right"></i> アカウント設定</a></li>
    <li><a href="<%= site_path(current_user.site) %>"><i class="icon-chevron-right"></i> ブログTOP</a></li>
  </ul>
</div>

app/views/admins/show.html.erb
<div class="container">
  <h1 class="page-header"><%= current_user.name %>さんの記事一覧</h1>

  <%= render 'sidenavi' %>

  <div class="span8">
    <% @posts.each do |post| %>
      <h4><%= link_to post.title, site_post_path(post.site, post) %></h4>
      <p>コメント(<%= post.comments.length %>) <%= post.created_at.strftime("%Y/%m/%d %X") %></p>
      <p>
        <%= link_to 'Edit', edit_site_admin_post_path(post.site, post) %> |
        <%= link_to 'Destroy', site_admin_post_path(post.site, post), method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
      <hr>
    <% end %>
  </div>

</div>