config/routes.rb
Blog::Application.routes.draw do

  resources :sites do
    resources :posts, only: [:show] do
      resources :comments, only: [:create, :edit, :update, :destroy]
    end
    resource :admin, only: [:show] do
      resources :posts, except: [:show, :index], controller: 'admin/posts'
    end
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users

  root 'sites#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :site
  has_many :comments, dependent: :destroy
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :check_if_own_site_in_admin!

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.site = current_user.site

    respond_to do |format|
      if @post.save
        format.html { redirect_to site_post_path(@post.site, @post), notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to site_post_path(@post.site, @post), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to site_admin_path(@post.site) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :site_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments
    @comment = Comment.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for([@post.site, @post, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <h1 class="page-header"><%= link_to @post.site.title, site_path(@post.site) %></h1>
  <h2><%= @post.title %></h2>
  <p id="notice"><%= notice %></p>

  <p><%= @post.created_at.strftime("%Y/%m/%d %X") %> | コメント(<%= @post.comments.length %>)</p>

  <hr>
  <p><%= simple_format(@post.body) %></p>
  <hr>

  <!-- コメント投稿box -->
  <h4>Comment</h4>
  <% if current_user %>
    <%= render 'form' %>
  <% end %>

  <!-- コメント一覧 -->
  <% @comments.each do |comment| %>
    <p><%= comment.user.name %>さん | <%= comment.created_at.strftime("%Y/%m/%d %X") %>
      <% if comment.user == current_user %>
        ( <%= link_to 'Edit', edit_site_post_comment_path(comment.post.site, comment.post, comment) %> |
        <%= link_to 'Destroy', [@post.site, @post, comment], method: :delete, data: { confirm: 'Are you sure?' } %> )
      <% end %>
    </p>
    <p><%= simple_format(comment.comment) %></p>
    <hr>
  <% end %>

</div>